### ISSUE TITLE
How can I use clientId and clientSecret here instead of path to my credentials.json?

### ISSUE THREAD

**Issue by neeramrutia** [curtcommander/utils-google-drive#7]

**Comment by curtcommander** [comment]
You can pass the client id and client secrect directly when instantiating the `UtilsGDrive` class by using the `credentials` (rather than `pathCredentials`) property:

```
const utilsGDrive = new UtilsGDrive({
  credentials: credentialsGDrive,
  pathToken:  'path/to/tokenGDrive.json'
});
```

The data passed to the `credentials` property is usually downloaded from Google Cloud Platform and should take the following form:

```
interface Credentials$GoogleApi {
  installed: {
    client_secret: string;
    client_id: string;
    redirect_uris: string;
  }
}
```
